[[categories]]
name = "B站"
keywords = [ "B站", "b", "up" ]

[[categories]]
name = "抖音"
keywords = [ "抖", "音", "dy" ]

[[categories]]
name = "其他"
keywords = [ "清", "蒸", "云", "鸭" ]

[reject]
keywords = [ "广告", "代练", "加群", "互粉", "卖茶", "朋友推荐" ]